name: Docker Image Alpine With Rsync And Ssh

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    # Runs "every Monday" (see https://crontab.guru)
    - cron: '0 0 * * MON'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # ref: https://stackoverflow.com/a/60942437/2117999
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to DockerHub Registry
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Build and push based alpine-3.18 with rsync ssh
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./alpine-with-rsync-ssh/
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            ALPINE_VERSION=3.18
            ESSENTIAL_PACKAGES=openssh rsync tree
          tags: |
            ghcr.io/junxy/alpine:alpine3.18-rsync-ssh
            junxy/alpine:alpine3.18-rsync-ssh
            junxy/alpine:alpine3.18-rsync-ssh-${{ steps.date.outputs.date }}
          #junxy/alpine:${{ github.sha }}

      - name: Build and push based alpine-3.19 with rsync ssh
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./alpine-with-rsync-ssh/
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            ALPINE_VERSION=3.19
            ESSENTIAL_PACKAGES=openssh rsync tree
          tags: |
            ghcr.io/junxy/alpine:rsync-ssh
            ghcr.io/junxy/alpine:alpine3.19-rsync-ssh
            junxy/alpine:rsync-ssh
            junxy/alpine:alpine3.19-rsync-ssh
            junxy/alpine:rsync-ssh-${{ steps.date.outputs.date }}
            junxy/alpine:alpine3.19-rsync-ssh-${{ steps.date.outputs.date }}


      - name: Build and push based alpine-3.18 with node lts and rsync ssh
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./alpine-node-with-rsync-ssh/
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            ALPINE_VERSION=3.18
            NODE_VERSION=lts
            ESSENTIAL_PACKAGES=openssh rsync tree
          tags: |
            ghcr.io/junxy/alpine:alpine3.18-node-lts-rsync-ssh
            junxy/alpine:alpine3.18-node-lts-rsync-ssh
            junxy/alpine:alpine3.18-node-lts-rsync-ssh-${{ steps.date.outputs.date }}

      - name: Build and push based alpine-3.19 with node lts and rsync ssh
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./alpine-node-with-rsync-ssh/
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            ALPINE_VERSION=3.19
            NODE_VERSION=lts
            ESSENTIAL_PACKAGES=openssh rsync tree
          tags: |
            ghcr.io/junxy/alpine:node-lts-rsync-ssh
            ghcr.io/junxy/alpine:alpine3.19-node-lts-rsync-ssh
            junxy/alpine:node-lts-rsync-ssh
            junxy/alpine:alpine3.19-node-lts-rsync-ssh
            junxy/alpine:node-lts-rsync-ssh-${{ steps.date.outputs.date }}
            junxy/alpine:alpine3.19-node-lts-rsync-ssh-${{ steps.date.outputs.date }}


      - name: Build and push based alpine-3.18 with node lts and pnpm9
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./alpine-node-with-pnpm/
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            ALPINE_VERSION=3.18
            PNPM_VERSION=latest-9
          tags: |
            ghcr.io/junxy/alpine:alpine3.18-node-lts-pnpm9
            junxy/alpine:alpine3.18-node-lts-pnpm9
            junxy/alpine:alpine3.18-node-lts-pnpm9-${{ steps.date.outputs.date }}

      - name: Build and push based alpine-3.19 with node lts and pnpm9
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./alpine-node-with-pnpm/
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            ALPINE_VERSION=3.19
            PNPM_VERSION=latest-9
          tags: |
            ghcr.io/junxy/alpine:node-lts-pnpm9
            ghcr.io/junxy/alpine:alpine3.19-node-lts-pnpm9
            junxy/alpine:node-lts-pnpm9
            junxy/alpine:alpine3.19-node-lts-pnpm9
            junxy/alpine:node-lts-pnpm9-${{ steps.date.outputs.date }}
            junxy/alpine:alpine3.19-node-lts-pnpm9-${{ steps.date.outputs.date }}


      - name: Build and push based alpine-3.18 with node lts and pnpm9 rsync ssh
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./alpine-node-with-pnpm-rsync-ssh/
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            ALPINE_VERSION=3.18
            PNPM_VERSION=latest-9
            ESSENTIAL_PACKAGES=openssh tree rsync
            BUILD_DATA="${{ steps.date.outputs.date }}"

          tags: |
            ghcr.io/junxy/alpine:alpine3.18-node-lts-pnpm9-rsync-ssh
            junxy/alpine:alpine3.18-node-lts-pnpm9-rsync-ssh
            junxy/alpine:alpine3.18-node-lts-pnpm9-rsync-ssh-${{ steps.date.outputs.date }}

      - name: Build and push based alpine-3.19 with node lts and pnpm9 rsync ssh
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./alpine-node-with-pnpm-rsync-ssh/
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            ALPINE_VERSION=3.19
            PNPM_VERSION=latest-9
            ESSENTIAL_PACKAGES=openssh tree rsync curl
            BUILD_DATA="${{ steps.date.outputs.date }}"
          tags: |
            ghcr.io/junxy/alpine:node-lts-pnpm9-rsync-ssh
            ghcr.io/junxy/alpine:alpine3.19-node-lts-pnpm9-rsync-ssh
            junxy/alpine:node-lts-pnpm9-rsync-ssh
            junxy/alpine:alpine3.19-node-lts-pnpm9-rsync-ssh
            junxy/alpine:node-lts-pnpm9-rsync-ssh-${{ steps.date.outputs.date }}
            junxy/alpine:alpine3.19-node-lts-pnpm9-rsync-ssh-${{ steps.date.outputs.date }}
